"""
Django settings for hospital project.

Generated by 'django-admin startproject' using Django 3.2.25.

Works locally (MySQL on localhost, DEBUG on) and on Render (hosted MySQL via
DATABASE_URL, DEBUG off) without editing the file between the two.
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Render sets the RENDER environment variable automatically.
ON_RENDER = "RENDER" in os.environ


# SECURITY WARNING: keep the secret key used in production secret!
# Set SECRET_KEY as an environment variable on Render.
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-only-insecure-key-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults: True locally, False on Render. Override with the DEBUG env var.
DEBUG = os.environ.get("DEBUG", "False" if ON_RENDER else "True") == "True"

ALLOWED_HOSTS = [".onrender.com", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hospitalapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hospital.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hospital.wsgi.application'


# Database
# On Render: a hosted MySQL, configured through the DATABASE_URL env var,
#   e.g. mysql://USER:PASSWORD@HOST:PORT/DBNAME
# Locally: MySQL on localhost. Set DB_PASSWORD in your shell so the password
# stays out of the repo:
#   PowerShell:  $env:DB_PASSWORD="root"
#   cmd:         set DB_PASSWORD=root

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
    # Most cloud MySQL providers require SSL. PyMySQL only uses it when asked.
    if 'mysql' in DATABASES['default']['ENGINE']:
        import certifi
        DATABASES['default'].setdefault('OPTIONS', {})['ssl'] = {'ca': certifi.where()}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'hospital_db',
            'USER': 'root',
            'PASSWORD': os.environ.get("DB_PASSWORD", ""),
            'HOST': 'localhost',
            'PORT': '3306',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Render terminates HTTPS at its proxy; this makes Django see requests as secure.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'